name: Проверка
on: [push]
jobs:
  linter_hw3:
    name: Линтер HW3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.0
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: |
        cd HW3
        flake8
  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install pytest==8.0.1
        pip install numpy
    - name: Pytest
      run: |
        cd HW3
        python3 -m pytest
